# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DistMat <- function(M, cutoff, kernel = "bartlett", dist_fn = "Haversine") {
    .Call(`_conleyerrors_DistMat`, M, cutoff, kernel, dist_fn)
}

XeeXhC <- function(M, cutoff, X, e, n1, k, kernel = "bartlett", dist_fn = "Haversine") {
    .Call(`_conleyerrors_XeeXhC`, M, cutoff, X, e, n1, k, kernel, dist_fn)
}

Bal_XeeXhC <- function(dmat, X, e, n1, k) {
    .Call(`_conleyerrors_Bal_XeeXhC`, dmat, X, e, n1, k)
}

XeeXhC_Lg <- function(M, cutoff, X, e, n1, k, kernel = "bartlett", dist_fn = "Haversine") {
    .Call(`_conleyerrors_XeeXhC_Lg`, M, cutoff, X, e, n1, k, kernel, dist_fn)
}

TimeDist <- function(times, cutoff, X, e, n1, k) {
    .Call(`_conleyerrors_TimeDist`, times, cutoff, X, e, n1, k)
}

